addpath /songlab/aaron/research/fun_genom/active_work/chance
addpath /songlab/aaron/research/fun_genom/active_work/chance/chance_com

data_dirs={%'/songlab/aaron/research/fun_genom/data/broad_tfbs/normal',...
           %'/songlab/aaron/research/fun_genom/data/broad_tfbs/cancer',...
           %'/songlab/aaron/research/fun_genom/data/broad_histone_chipseq/normal',...
           %'/songlab/aaron/research/fun_genom/data/broad_histone_chipseq/cancer',...
           %'/songlab/aaron/research/fun_genom/data/yale_chipseq/normal',...
           %'/songlab/aaron/research/fun_genom/data/yale_chipseq/cancer',...
'/songlab/aaron/research/fun_genom/data/haib_tfbs/normal',...
'/songlab/aaron/research/fun_genom/data/haib_tfbs/cancer'};

ctr_strs={%'Control','Control','Control','Control','Input','Input',...
'Rxlch','Rxlch'};

fnames={%'broad_tfbs_normal.mat',...
        %'broad_tfbs_cancer.mat',...
        %'broad_histone_chipseq_normal.mat',...
        %'broad_histone_chipseq_cancer.mat',...
        %'yale_chipseq_normal.mat',...
        %'yale_chipseq_cancer.mat',...
'haib_tfbs_normal.mat',...
'haib_tfbs_cancer.mat'};

for i=1:2
[cinull, zvalnull, cialt, zvalalt, pnull, palt]= ...
    comp_chance_fdr(data_dirs{i},ctr_strs{i});
save(['/songlab/aaron/research/fun_genom/data/' fnames{i}])
end